/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccesibilidadRouteImport } from './routes/accesibilidad'
import { Route as AlbumRouteImport } from './routes/album'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as JuguetesRouteImport } from './routes/juguetes'
import { Route as MisionesRouteImport } from './routes/misiones'
import { Route as PreguntasRouteImport } from './routes/preguntas'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as AventurasIndexRouteImport } from './routes/aventuras/index'
import { Route as AventurasIdRouteImport } from './routes/aventuras/$id'
import { Route as ExploraIndexRouteImport } from './routes/explora/index'
import { Route as ExploraTemaRouteImport } from './routes/explora/$tema'
import { Route as JuegosIndexRouteImport } from './routes/juegos/index'
import { Route as JuegosIdRouteImport } from './routes/juegos/$id'
import { Route as LeerIndexRouteImport } from './routes/leer/index'
import { Route as LeerIdRouteImport } from './routes/leer/$id'
import { Route as PadresIndexRouteImport } from './routes/padres/index'
import { Route as PadresSlugRouteImport } from './routes/padres/$slug'
import { Route as PersonajesIndexRouteImport } from './routes/personajes/index'
import { Route as PersonajesSlugRouteImport } from './routes/personajes/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccesibilidadRoute = AccesibilidadRouteImport.update({
  id: '/accesibilidad',
  path: '/accesibilidad',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumRoute = AlbumRouteImport.update({
  id: '/album',
  path: '/album',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const JuguetesRoute = JuguetesRouteImport.update({
  id: '/juguetes',
  path: '/juguetes',
  getParentRoute: () => rootRouteImport,
} as any)
const MisionesRoute = MisionesRouteImport.update({
  id: '/misiones',
  path: '/misiones',
  getParentRoute: () => rootRouteImport,
} as any)
const PreguntasRoute = PreguntasRouteImport.update({
  id: '/preguntas',
  path: '/preguntas',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const AventurasIndexRoute = AventurasIndexRouteImport.update({
  id: '/aventuras/',
  path: '/aventuras/',
  getParentRoute: () => rootRouteImport,
} as any)
const AventurasIdRoute = AventurasIdRouteImport.update({
  id: '/aventuras/$id',
  path: '/aventuras/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploraIndexRoute = ExploraIndexRouteImport.update({
  id: '/explora/',
  path: '/explora/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploraTemaRoute = ExploraTemaRouteImport.update({
  id: '/explora/$tema',
  path: '/explora/$tema',
  getParentRoute: () => rootRouteImport,
} as any)
const JuegosIndexRoute = JuegosIndexRouteImport.update({
  id: '/juegos/',
  path: '/juegos/',
  getParentRoute: () => rootRouteImport,
} as any)
const JuegosIdRoute = JuegosIdRouteImport.update({
  id: '/juegos/$id',
  path: '/juegos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LeerIndexRoute = LeerIndexRouteImport.update({
  id: '/leer/',
  path: '/leer/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeerIdRoute = LeerIdRouteImport.update({
  id: '/leer/$id',
  path: '/leer/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PadresIndexRoute = PadresIndexRouteImport.update({
  id: '/padres/',
  path: '/padres/',
  getParentRoute: () => rootRouteImport,
} as any)
const PadresSlugRoute = PadresSlugRouteImport.update({
  id: '/padres/$slug',
  path: '/padres/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonajesIndexRoute = PersonajesIndexRouteImport.update({
  id: '/personajes/',
  path: '/personajes/',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonajesSlugRoute = PersonajesSlugRouteImport.update({
  id: '/personajes/$slug',
  path: '/personajes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accesibilidad': typeof AccesibilidadRoute
  '/album': typeof AlbumRoute
  '/contacto': typeof ContactoRoute
  '/juguetes': typeof JuguetesRoute
  '/misiones': typeof MisionesRoute
  '/preguntas': typeof PreguntasRoute
  '/privacidad': typeof PrivacidadRoute
  '/sobre': typeof SobreRoute
  '/aventuras/$id': typeof AventurasIdRoute
  '/explora/$tema': typeof ExploraTemaRoute
  '/juegos/$id': typeof JuegosIdRoute
  '/leer/$id': typeof LeerIdRoute
  '/padres/$slug': typeof PadresSlugRoute
  '/personajes/$slug': typeof PersonajesSlugRoute
  '/aventuras/': typeof AventurasIndexRoute
  '/explora/': typeof ExploraIndexRoute
  '/juegos/': typeof JuegosIndexRoute
  '/leer/': typeof LeerIndexRoute
  '/padres/': typeof PadresIndexRoute
  '/personajes/': typeof PersonajesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accesibilidad': typeof AccesibilidadRoute
  '/album': typeof AlbumRoute
  '/contacto': typeof ContactoRoute
  '/juguetes': typeof JuguetesRoute
  '/misiones': typeof MisionesRoute
  '/preguntas': typeof PreguntasRoute
  '/privacidad': typeof PrivacidadRoute
  '/sobre': typeof SobreRoute
  '/aventuras/$id': typeof AventurasIdRoute
  '/explora/$tema': typeof ExploraTemaRoute
  '/juegos/$id': typeof JuegosIdRoute
  '/leer/$id': typeof LeerIdRoute
  '/padres/$slug': typeof PadresSlugRoute
  '/personajes/$slug': typeof PersonajesSlugRoute
  '/aventuras': typeof AventurasIndexRoute
  '/explora': typeof ExploraIndexRoute
  '/juegos': typeof JuegosIndexRoute
  '/leer': typeof LeerIndexRoute
  '/padres': typeof PadresIndexRoute
  '/personajes': typeof PersonajesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accesibilidad': typeof AccesibilidadRoute
  '/album': typeof AlbumRoute
  '/contacto': typeof ContactoRoute
  '/juguetes': typeof JuguetesRoute
  '/misiones': typeof MisionesRoute
  '/preguntas': typeof PreguntasRoute
  '/privacidad': typeof PrivacidadRoute
  '/sobre': typeof SobreRoute
  '/aventuras/$id': typeof AventurasIdRoute
  '/explora/$tema': typeof ExploraTemaRoute
  '/juegos/$id': typeof JuegosIdRoute
  '/leer/$id': typeof LeerIdRoute
  '/padres/$slug': typeof PadresSlugRoute
  '/personajes/$slug': typeof PersonajesSlugRoute
  '/aventuras/': typeof AventurasIndexRoute
  '/explora/': typeof ExploraIndexRoute
  '/juegos/': typeof JuegosIndexRoute
  '/leer/': typeof LeerIndexRoute
  '/padres/': typeof PadresIndexRoute
  '/personajes/': typeof PersonajesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accesibilidad'
    | '/album'
    | '/contacto'
    | '/juguetes'
    | '/misiones'
    | '/preguntas'
    | '/privacidad'
    | '/sobre'
    | '/aventuras/$id'
    | '/explora/$tema'
    | '/juegos/$id'
    | '/leer/$id'
    | '/padres/$slug'
    | '/personajes/$slug'
    | '/aventuras/'
    | '/explora/'
    | '/juegos/'
    | '/leer/'
    | '/padres/'
    | '/personajes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accesibilidad'
    | '/album'
    | '/contacto'
    | '/juguetes'
    | '/misiones'
    | '/preguntas'
    | '/privacidad'
    | '/sobre'
    | '/aventuras/$id'
    | '/explora/$tema'
    | '/juegos/$id'
    | '/leer/$id'
    | '/padres/$slug'
    | '/personajes/$slug'
    | '/aventuras'
    | '/explora'
    | '/juegos'
    | '/leer'
    | '/padres'
    | '/personajes'
  id:
    | '__root__'
    | '/'
    | '/accesibilidad'
    | '/album'
    | '/contacto'
    | '/juguetes'
    | '/misiones'
    | '/preguntas'
    | '/privacidad'
    | '/sobre'
    | '/aventuras/$id'
    | '/explora/$tema'
    | '/juegos/$id'
    | '/leer/$id'
    | '/padres/$slug'
    | '/personajes/$slug'
    | '/aventuras/'
    | '/explora/'
    | '/juegos/'
    | '/leer/'
    | '/padres/'
    | '/personajes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccesibilidadRoute: typeof AccesibilidadRoute
  AlbumRoute: typeof AlbumRoute
  ContactoRoute: typeof ContactoRoute
  JuguetesRoute: typeof JuguetesRoute
  MisionesRoute: typeof MisionesRoute
  PreguntasRoute: typeof PreguntasRoute
  PrivacidadRoute: typeof PrivacidadRoute
  SobreRoute: typeof SobreRoute
  AventurasIdRoute: typeof AventurasIdRoute
  ExploraTemaRoute: typeof ExploraTemaRoute
  JuegosIdRoute: typeof JuegosIdRoute
  LeerIdRoute: typeof LeerIdRoute
  PadresSlugRoute: typeof PadresSlugRoute
  PersonajesSlugRoute: typeof PersonajesSlugRoute
  AventurasIndexRoute: typeof AventurasIndexRoute
  ExploraIndexRoute: typeof ExploraIndexRoute
  JuegosIndexRoute: typeof JuegosIndexRoute
  LeerIndexRoute: typeof LeerIndexRoute
  PadresIndexRoute: typeof PadresIndexRoute
  PersonajesIndexRoute: typeof PersonajesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accesibilidad': {
      id: '/accesibilidad'
      path: '/accesibilidad'
      fullPath: '/accesibilidad'
      preLoaderRoute: typeof AccesibilidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/album': {
      id: '/album'
      path: '/album'
      fullPath: '/album'
      preLoaderRoute: typeof AlbumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/juguetes': {
      id: '/juguetes'
      path: '/juguetes'
      fullPath: '/juguetes'
      preLoaderRoute: typeof JuguetesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/misiones': {
      id: '/misiones'
      path: '/misiones'
      fullPath: '/misiones'
      preLoaderRoute: typeof MisionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preguntas': {
      id: '/preguntas'
      path: '/preguntas'
      fullPath: '/preguntas'
      preLoaderRoute: typeof PreguntasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aventuras/': {
      id: '/aventuras/'
      path: '/aventuras'
      fullPath: '/aventuras/'
      preLoaderRoute: typeof AventurasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aventuras/$id': {
      id: '/aventuras/$id'
      path: '/aventuras/$id'
      fullPath: '/aventuras/$id'
      preLoaderRoute: typeof AventurasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explora/': {
      id: '/explora/'
      path: '/explora'
      fullPath: '/explora/'
      preLoaderRoute: typeof ExploraIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explora/$tema': {
      id: '/explora/$tema'
      path: '/explora/$tema'
      fullPath: '/explora/$tema'
      preLoaderRoute: typeof ExploraTemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/juegos/': {
      id: '/juegos/'
      path: '/juegos'
      fullPath: '/juegos/'
      preLoaderRoute: typeof JuegosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/juegos/$id': {
      id: '/juegos/$id'
      path: '/juegos/$id'
      fullPath: '/juegos/$id'
      preLoaderRoute: typeof JuegosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leer/': {
      id: '/leer/'
      path: '/leer'
      fullPath: '/leer/'
      preLoaderRoute: typeof LeerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leer/$id': {
      id: '/leer/$id'
      path: '/leer/$id'
      fullPath: '/leer/$id'
      preLoaderRoute: typeof LeerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/padres/': {
      id: '/padres/'
      path: '/padres'
      fullPath: '/padres/'
      preLoaderRoute: typeof PadresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/padres/$slug': {
      id: '/padres/$slug'
      path: '/padres/$slug'
      fullPath: '/padres/$slug'
      preLoaderRoute: typeof PadresSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personajes/': {
      id: '/personajes/'
      path: '/personajes'
      fullPath: '/personajes/'
      preLoaderRoute: typeof PersonajesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personajes/$slug': {
      id: '/personajes/$slug'
      path: '/personajes/$slug'
      fullPath: '/personajes/$slug'
      preLoaderRoute: typeof PersonajesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccesibilidadRoute: AccesibilidadRoute,
  AlbumRoute: AlbumRoute,
  ContactoRoute: ContactoRoute,
  JuguetesRoute: JuguetesRoute,
  MisionesRoute: MisionesRoute,
  PreguntasRoute: PreguntasRoute,
  PrivacidadRoute: PrivacidadRoute,
  SobreRoute: SobreRoute,
  AventurasIdRoute: AventurasIdRoute,
  ExploraTemaRoute: ExploraTemaRoute,
  JuegosIdRoute: JuegosIdRoute,
  LeerIdRoute: LeerIdRoute,
  PadresSlugRoute: PadresSlugRoute,
  PersonajesSlugRoute: PersonajesSlugRoute,
  AventurasIndexRoute: AventurasIndexRoute,
  ExploraIndexRoute: ExploraIndexRoute,
  JuegosIndexRoute: JuegosIndexRoute,
  LeerIndexRoute: LeerIndexRoute,
  PadresIndexRoute: PadresIndexRoute,
  PersonajesIndexRoute: PersonajesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
